import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f0fcf9",
        "surface-dim": "#d1dcda",
        "surface-bright": "#f0fcf9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eaf6f3",
        "surface-container": "#e5f0ed",
        "surface-container-high": "#dfebe8",
        "surface-container-highest": "#d9e5e2",
        "on-surface": "#131d1c",
        "on-surface-variant": "#404947",
        "inverse-surface": "#283231",
        "inverse-on-surface": "#e8f3f0",
        outline: "#707977",
        "outline-variant": "#bfc8c6",
        "surface-tint": "#2f6760",
        primary: "#2f6760",
        "on-primary": "#ffffff",
        "primary-container": "#7eb6ad",
        "on-primary-container": "#064841",
        "inverse-primary": "#99d1c8",
        secondary: "#635e53",
        "on-secondary": "#ffffff",
        "secondary-container": "#e9e2d3",
        "on-secondary-container": "#696458",
        tertiary: "#7b5900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#d1a54c",
        "on-tertiary-container": "#543c00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#b4eee4",
        "primary-fixed-dim": "#99d1c8",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#124f48",
        "secondary-fixed": "#e9e2d3",
        "secondary-fixed-dim": "#cdc6b8",
        "on-secondary-fixed": "#1e1b13",
        "on-secondary-fixed-variant": "#4b463c",
        "tertiary-fixed": "#ffdea4",
        "tertiary-fixed-dim": "#eec063",
        "on-tertiary-fixed": "#261900",
        "on-tertiary-fixed-variant": "#5d4200",
        background: "#f0fcf9",
        "on-background": "#131d1c",
        "surface-variant": "#d9e5e2",
        "accent-coral": "#FF8A7A",
        success: "#4CAF50",
      },
      fontFamily: {
        quicksand: ["Quicksand", "sans-serif"],
        "public-sans": ["Public Sans", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "headline-sm": ["Quicksand", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "body-sm": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", fontWeight: "700", letterSpacing: "-0.01em" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "20px",
        gutter: "16px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "40px",
      },
      boxShadow: {
        "soft": "0 8px 20px rgba(126, 182, 173, 0.15)",
        "soft-lg": "0 12px 24px rgba(126, 182, 173, 0.2)",
      },
    },
  },
  plugins: [],
}

export default config
