export const designColors = {
  "warm-cream": "#fdf5e6",
  surface: "#f0fcf9",
  "surface-dim": "#d1dcda",
  "surface-bright": "#f0fcf9",
  "surface-container-lowest": "#ffffff",
  "surface-container-low": "#eaf6f3",
  "surface-container": "#e5f0ed",
  "surface-container-high": "#dfebe8",
  "surface-container-highest": "#d9e5e2",
  "on-surface": "#131d1c",
  "on-surface-variant": "#404947",
  "inverse-surface": "#283231",
  "inverse-on-surface": "#e8f3f0",
  outline: "#707977",
  "outline-variant": "#bfc8c6",
  "surface-tint": "#2f6760",
  primary: "#2f6760",
  "on-primary": "#ffffff",
  "primary-container": "#7eb6ad",
  "on-primary-container": "#064841",
  "inverse-primary": "#99d1c8",
  secondary: "#635e53",
  "on-secondary": "#ffffff",
  "secondary-container": "#e9e2d3",
  "on-secondary-container": "#696458",
  tertiary: "#7b5900",
  "on-tertiary": "#ffffff",
  "tertiary-container": "#d1a54c",
  "on-tertiary-container": "#543c00",
  error: "#ba1a1a",
  "on-error": "#ffffff",
  "error-container": "#ffdad6",
  "on-error-container": "#93000a",
  "primary-fixed": "#b4eee4",
  "primary-fixed-dim": "#99d1c8",
  "on-primary-fixed": "#00201c",
  "on-primary-fixed-variant": "#124f48",
  "secondary-fixed": "#e9e2d3",
  "secondary-fixed-dim": "#cdc6b8",
  "on-secondary-fixed": "#1e1b13",
  "on-secondary-fixed-variant": "#4b463c",
  "tertiary-fixed": "#ffdea4",
  "tertiary-fixed-dim": "#eec063",
  "on-tertiary-fixed": "#261900",
  "on-tertiary-fixed-variant": "#5d4200",
  background: "#f0fcf9",
  "on-background": "#131d1c",
  "surface-variant": "#d9e5e2",
  "accent-coral": "#ff8a7a",
  success: "#4caf50",
} as const

export const designTypography = {
  "headline-lg": {
    fontFamily: "Quicksand",
    fontSize: "32px",
    fontWeight: "700",
    lineHeight: "40px",
    letterSpacing: "-0.02em",
  },
  "headline-lg-mobile": {
    fontFamily: "Quicksand",
    fontSize: "26px",
    fontWeight: "700",
    lineHeight: "32px",
    letterSpacing: "-0.01em",
  },
  "headline-md": {
    fontFamily: "Quicksand",
    fontSize: "24px",
    fontWeight: "600",
    lineHeight: "32px",
    letterSpacing: "0",
  },
  "headline-sm": {
    fontFamily: "Quicksand",
    fontSize: "20px",
    fontWeight: "600",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  "body-lg": {
    fontFamily: "Public Sans",
    fontSize: "18px",
    fontWeight: "400",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  "body-md": {
    fontFamily: "Public Sans",
    fontSize: "16px",
    fontWeight: "400",
    lineHeight: "24px",
    letterSpacing: "0",
  },
  "body-sm": {
    fontFamily: "Public Sans",
    fontSize: "14px",
    fontWeight: "400",
    lineHeight: "20px",
    letterSpacing: "0",
  },
  "label-md": {
    fontFamily: "Public Sans",
    fontSize: "12px",
    fontWeight: "600",
    lineHeight: "16px",
    letterSpacing: "0.05em",
  },
  "label-xs": {
    fontFamily: "Public Sans",
    fontSize: "10px",
    fontWeight: "700",
    lineHeight: "14px",
    letterSpacing: "0",
  },
  "display-timer": {
    fontFamily: "Quicksand",
    fontSize: "48px",
    fontWeight: "700",
    lineHeight: "52px",
    letterSpacing: "0",
  },
  "display-hero": {
    fontFamily: "Quicksand",
    fontSize: "80px",
    fontWeight: "700",
    lineHeight: "88px",
    letterSpacing: "0",
  },
} as const

export const designRadii = {
  sm: "0.25rem",
  DEFAULT: "0.5rem",
  md: "0.75rem",
  lg: "1rem",
  xl: "1.5rem",
  "2xl": "1rem",
  "3xl": "1.5rem",
  full: "9999px",
} as const

export const designSpacing = {
  base: "8px",
  "container-margin": "20px",
  gutter: "16px",
  "stack-sm": "12px",
  "stack-md": "24px",
  "stack-lg": "40px",
  "touch": "44px",
  "field": "56px",
  "nav": "80px",
} as const

export const designShadows = {
  soft: "0 8px 20px rgba(126, 182, 173, 0.15)",
  "soft-lg": "0 12px 24px rgba(126, 182, 173, 0.2)",
  "nav-soft": "0 -8px 20px rgba(126, 182, 173, 0.15)",
  "primary-glow": "0 8px 20px rgba(47, 103, 96, 0.2)",
} as const

export const stitchScreens = [
  "create_baby_profile",
  "create_your_account",
  "detailed_sleep_tracking_timers",
  "feeding_entry_forms",
  "feeding_log_timers",
  "functional_nalagrow_dashboard",
  "growth_tracking_charts",
  "interactive_feeding_log",
  "interactive_growth_tracking",
  "interactive_nalagrow_dashboard",
  "login_to_nalagrow",
  "manage_baby_profiles_switching",
  "milestones_timeline",
  "nalagrow_dashboard",
  "quick_log_menu_overlay",
  "record_bottle_feed_detail",
  "record_solids_feed_detail",
  "solids_feeding_reactions_log",
  "nalagrow_visual_framework",
] as const

export const componentInventory = [
  "Button",
  "Input",
  "Card",
  "Chip",
  "Avatar",
  "SegmentedControl",
  "Spinner",
  "ProgressBar",
  "FAB",
  "SuccessOverlay",
  "Timer",
  "StatCard",
  "Timeline",
  "BottomSheet",
  "Dropdown",
  "PillButton",
  "StepperInput",
  "SideSelector",
  "ProfileCard",
  "PhotoUpload",
  "OAuthButton",
  "PageShell",
  "PageHeader",
  "ProfileSwitcher",
  "ChartWrapper",
  "GrowthPercentileChart",
  "MetricCard",
  "QuickLogGrid",
  "ReactionSelector",
] as const

export type DesignColorToken = keyof typeof designColors
export type DesignTypographyToken = keyof typeof designTypography
export type StitchScreen = (typeof stitchScreens)[number]
export type ComponentInventoryItem = (typeof componentInventory)[number]
